# ST2195 Class Assignment 1b (Python)

## About the Assignment

This is the ***Python*** part of ST2195 Class Assignment 1, which covers topics from Blocks 1 & 2 of the "ST2195 Programming for Data Science" course.

**Instructions:**

1. For each question, run the starter code first to create the necessary data structures/variables before attempting the subsequent tasks.

2. After this, follow the sequence of the tasks, and provide your Python code to address each task in the respective code cells.

3. In all cases, a single line of code is sufficient to achieve the task. However, you can use multiple lines of code if necessary.



## Question 1 (total 10 marks)

In [2]:
# Suppose we have the following variables: phrase and amount
# -- run this code first --
phrase = "prices are final and not subject to negotiation"
amount = "39"

In [3]:
# Task 1.1 - Write Python code to show how many characters are contained in 'phrase' variable [2 marks]
# -- insert your code below --
nchar = len(phrase)
print(nchar)

47


In [6]:
# Task 1.2 - Write Python code to display the first 5 characters of the 'phrase' variable [2 marks]
# -- insert your code below --
print(phrase[:5])

price


In [7]:
# Task 1.3 - Write Python code to find the index/position where the word 'items' starts [2 marks]
# -- insert your code below --
print(phrase.find("items"))

-1


In [8]:
# Task 1.4 - Write Python code to split the phrase into individual words [2 marks]
# -- insert your code below --
print(phrase.split(" "))

['prices', 'are', 'final', 'and', 'not', 'subject', 'to', 'negotiation']


In [12]:
# Task 1.5 - Write Python code to convert data type of 'amount' variable to integer [2 marks]
# -- insert your code below --
int(amount)

39

## Question 2 (total 12 marks)

In [13]:
# Suppose we define the following variables A, B, C, D in Python
# -- run this code first --
A = [2, 15, 1, 12, 5, 7, 10]
B = {'python','r','python','c', 'java','r','c++'}
C = {"brand": "Toyota", "model": "Corolla", "colour": "blue", "year": 2020}
D = ('A', A, C)

In [16]:
# Task 2.1 - Write Python code to change the last element of A to 10 [2 marks]
# -- insert your code below --
A[6] = 10

In [ ]:
# Task 2.2 - Write Python code to add a new element with value 'last' to the end of the list A [2 marks]
# -- insert your code below --
A.append('last')

In [17]:
# Task 2.3 - Write Python code to delete 'c++' from B [2 marks]
# -- insert your code below --
B.remove('c++')

In [20]:
# Task 2.4 - Write Python code to add a new item in C with key as "capacity" and value as 1600 [2 marks] 
# -- insert your code below --
C["capacity"] = 1600

In [23]:
# Task 2.5 - Write Python code to display all key-value pairs from C [2 marks]
# -- insert your code below --
for key, value in C.items():
    print(f"Key: {key}, Value: {value}")

Key: brand, Value: Toyota
Key: model, Value: Corolla
Key: colour, Value: blue
Key: year, Value: 2020
Key: capacity, Value: 1600


In [24]:
# Task 2.6 - Write Python code to sum up the first 3 values of the 2nd element in D [2 marks]
# -- insert your code below --
sum(D[1][:3])

18

## Question 3 -- Numpy (total 10 marks)

In [25]:
# Suppose we have an 2-dimensional array of random numbers stored in variable named 'array1'
# -- run this code first --
import numpy as np
np.random.seed(100)
array1 = np.random.random((5,3))
array1

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912],
       [0.67074908, 0.82585276, 0.13670659],
       [0.57509333, 0.89132195, 0.20920212],
       [0.18532822, 0.10837689, 0.21969749]])

In [26]:
# Task 3.1 - Write Python code to show the number of rows and columns in the array [2 marks]
# -- insert your code below --
array1.shape

(5, 3)

In [28]:
# Task 3.2 - Write Python code to display the first and third columns' values in the array [2 marks]
# -- insert your code below --
array1[:,[0,2]]

array([[0.54340494, 0.42451759],
       [0.84477613, 0.12156912],
       [0.67074908, 0.13670659],
       [0.57509333, 0.20920212],
       [0.18532822, 0.21969749]])

In [31]:
# Task 3.3 - Write Python code to display the first 3 rows and first 2 columns of the array [2 marks]
# -- insert your code below --
array1[:3,:2]

array([[0.54340494, 0.27836939],
       [0.84477613, 0.00471886],
       [0.67074908, 0.82585276]])

In [33]:
# Task 3.4 - Write Python code to multiply all values in the array by 100 [2 marks]
# -- insert your code below --
array1 * 100

array([[54.34049418, 27.83693851, 42.45175907],
       [84.47761323,  0.47188562, 12.15691208],
       [67.07490847, 82.58527551, 13.67065897],
       [57.50933294, 89.13219543, 20.92021221],
       [18.53282196, 10.83768905, 21.96974926]])

In [35]:
# Task 3.5 - Write Python code to sort the array so that the values in each row are in ascending order [2 marks]
# -- insert your code below --
np.sort(array1,axis=1)

array([[0.27836939, 0.42451759, 0.54340494],
       [0.00471886, 0.12156912, 0.84477613],
       [0.13670659, 0.67074908, 0.82585276],
       [0.20920212, 0.57509333, 0.89132195],
       [0.10837689, 0.18532822, 0.21969749]])

## Question 4 -- Pandas (total 18 marks)

In [45]:
# We will use the Tips dataset for this question
#    https://www.geeksforgeeks.org/data-science/seaborn-datasets-for-data-science/#1-tips-dataset

# We import relevant libraries and load the tips dataset from seaborn
# -- run this code first --

# !pip install seaborn  #to install seaborn if needed
import pandas as pd
import seaborn as sns
df = sns.load_dataset('tips')

HTTPError: HTTP Error 503: Backend unavailable, connection timeout

In [ ]:
# Task 4.1 - Write Python code to show the data types of all columns of the dataset [2 marks]
# -- insert your code below --


In [ ]:
# Task 4.2 - Write Python code to show the first 15 rows of the dataset [2 marks]
# -- insert your code below --


In [ ]:
# Task 4.3 - Write Python code to show some summary statistics for all numeric variables in the dataset [2 marks]
# -- insert your code below --


In [ ]:
# Task 4.4 - Write Python code to show the rows where the "time" is "Dinner" and "total_bill" is above 40 [2 marks]
# -- insert your code below --


In [ ]:
# Task 4.5 - Write Python code to subset to the first 2 columns and last 3 columns, and store result in df_subset [3 marks]
# -- insert your code below --


In [ ]:
# Task 4.6 - Write Python code to show the rows where the ratio of "tip" to "total_bill" is above 30% [3 marks]
# Note: If you wish, you can create a new column to store this ratio in the dataframe "df" 
# -- insert your code below --


In [ ]:
# Task 4.7 - Write Python code to extract the maximum and minimum values of "total_bill" [2 marks]
# -- insert your code below --


In [ ]:
# Task 4.8 - Write Python code to make a copy of the dataframe "df" and save as another dataframe "df_backup" [2 marks]
# -- insert your code below --
